# Generated by Django 5.1.1 on 2024-09-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='unit',
        ),
    ]
